FROM openjdk:17
LABEL maintainer="talukdar.mca@gmail.com"

ADD **/target/springsection9-0.0.1-SNAPSHOT.jar springsection9-0.0.1-SNAPSHOT.jar

EXPOSE 8080
ENTRYPOINT ["java","-jar","/springsection9-0.0.1-SNAPSHOT.jar"]