pipeline{
	agent any
	environment{
		NEW_VERSION='1.3.0'
	}
	stages{
		stage('Init'){
			steps{
			  echo "Hi this is babul ${NEW_VERSION}"
			}
		}
		stage('maven build'){
			steps{
				sh 'mvn -f springsecsection9/pom.xml clean package'
			}
			post{
				success {
                    		echo 'Now Archiving artifacts'
                    		archiveArtifacts artifacts:'**/*.war'
                		}
		
			}
		}
		stage('docker build'){
			steps{
				echo 'Deploy maven project'
				sh 'docker build  -t babultalukdar/springSecurityWeb -f springsecsection9/Dockerfile .'
			}
		}
	}
	
}
