pipeline{
	agent any
	stages{
		stage('Init'){
			steps{
				'Hi this is babul'
			}
		}
		stage('Build'){
			steps{
				'Build sample maven project'
			}
		}
		stage('Deploy'){
			steps{
				'Deploy maven project'
			}
		}
	}
}
