pipeline{
	agent any
	environment{
		NEW_VERSION='1.3.0'
	}
	stages{
		stage('Init'){
			steps{
			  echo "Hi this is babul ${NEW_VERSION}"
			}
		}
		stage('Build'){
			steps{
				sh 'mvn -f springsecsection9/pom.xml clean package'
			}
		}
		stage('Deploy'){
			steps{
				echo 'Deploy maven project'
			}
		}
	}
	post{
		success {
                    echo 'Now Archiving'
                }
		
	}
}
